name: "periprice"            
version: "1.0"
config-version: 2             

profile: "periprice"          


model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]


target-path: "target"         # compiled SQL
log-path: "logs"              # logs


models:
  periprice:
    sources:
      +materialized: view     
    staging:
      +materialized: view     
    intermediate:
      +materialized: table    
    marts:
      +materialized: table    
      +persist_docs:
        relation: true
        columns: true         